[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bufr"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "scipy",
    "scikit-image",
    "opencv-python",
    "matplotlib",
    "Pillow",
    "tabulate",
    "pyyaml",
    "wilds",
    "wandb",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
bufr-pretrain = "bufr.pretrain:main"
bufr-adapt = "bufr.adapt:main"
bufr-run = "bufr.bufr:main"
bufr-save-train-stats = "bufr.save_train_stats:main"
